version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
  whisper:
    image: ghcr.io/ggerganov/whisper.cpp:latest
    ports:
      - "9000:9000"
    restart: unless-stopped
volumes:
  ollama_data:
