services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: apps/backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false # Set this in the Render dashboard for security
